### PR TITLE
set up clojars deployment

### PR DESCRIPTION
**Pull request by milt**
Using our lovely yet actions.

### CODE REVIEW

**Comment by kelvinqian00** [comment]
Silly request but don't forget the Clojars badge on the README!

**Comment by milt** [comment]
> Silly request but don't forget the Clojars badge on the README!

badged!

**Comment by kelvinqian00** [comment]
Ok for some reason the `v1.2.6-test-0` tag did _not_ get pushed up to Clojars. (This was a big reason why I asked for the badge - it provides an instant way to check the deployment on Clojars.) You can confirm this by going to the Yet Analytics Clojars page: https://clojars.org/groups/com.yetanalytics.

**Comment by milt** [comment]
> Ok for some reason the v1.2.6-test-0 tag did not get pushed up to Clojars.

intentional, I set `publish` to false. I wanted to make sure the artifact it built had the right stuff, it did.

**Comment by kelvinqian00** [comment]
Ok (I forgot I added that feature lol). Make sure to deploy a SNAPSHOT version to check that Clojars deployment works then.

**Comment by kelvinqian00** [comment]
Snapshot has been pushed - next step is to test the Clojars artifact on downstream apps like lrsql to ensure that it works.

**Review by kelvinqian00 — APPROVED** [review]
Works on lrsql

**Pull request merged**
